theme: minima
title: "youngnvk"

minima:
  social_links:
    github: ynvk404
    facebook: https://www.facebook.com/young.nvk
    instagram: https://www.instagram.com/young.nvk/
    email: youngnvk@gmail.com

exclude:
  - README.md
